### ISSUE TITLE
SSL/TLS Not Supported

### ISSUE THREAD

**Issue by martindale** [felixge/node-form-data#104]
When attempting to submit to an https endpoint, the following error is generated:

```
Error: Protocol:https not supported.
    at Object.exports.request (http.js:1841:11)
    at FormData.submit (/some/random/path/node_modules/form-data/lib/form_data.js:312:20)
    at Request.<anonymous> (/some/random/path/lib/Engine.js:69:16)
    at Request.emit (events.js:95:17)
    at Request.onRequestResponse (/some/random/path/node_modules/request/request.js:1139:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData [as ondata] (http.js:1584:20)
    at TCP.onread (net.js:528:27)
```

**Comment by alexindigo** [comment]
I updated tests, to use local server (with self-signed certificate) and it works all along.
Here is Travis with `0.10`, `0.12` and `io.js` – https://travis-ci.org/felixge/node-form-data/builds/66670575

Can you show me your code that generates this error?

Thank you.

**Comment by alexindigo** [comment]
Seems like no longer an issue.
